version: '3'
services:
  backendnanolite:
    build: ./php
    image: laravel:latest
    container_name: backendnanolite
    hostname: "backendnanolite"
    volumes:
      - ./src:/var/www/html
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    working_dir: /var/www/html
    depends_on: 
      - db_backendnanolite

  db_backendnanolite:
    image: mariadb:10.2
    container_name: db_backendnanolite
    restart: unless-stopped
    tty: true
    ports:
      - "63306:3306"
    volumes:
      - ./database/data:/var/lib/mysql
      - ./conf.d:/etc/mysql/conf.d:ro
    environment:
      MYSQL_DATABASE: your_database
      MYSQL_USER: nanolite
      MYSQL_PASSWORD: nanolite1234
      MYSQL_ROOT_PASSWORD: nanolite12345
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql

  nginx_backendnanolite:
    build: ./nginx
    image: nginx_backendnanolite:latest
    container_name: nginx_backendnanolite
    hostname: "nginx_backendnanolite"
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backendnanolite